FROM python:3.12 as install-deps

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "${PYTHONPATH}:/code/"
ENV PIP_DEFAULT_TIMEOUT=100

WORKDIR /code

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /code/

#RUN apt-get update
#RUN apt-get install -y build-essential  # for web3.py

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

FROM install-deps AS copy-project-and-run

COPY ./fapp /code/fapp/

CMD uvicorn fapp.main:app --host 0.0.0.0 --port 8090 --reload